#!/usr/bin/env bash
#loop in list format
i=1
while [ $i -le 100 ]
do
    echo "$i"
    if ! (( i % 5 )) && ! (( i % 3 ))
    then
	echo "Fizzbuzz"
    elif ! (( i % 3 ))
	 then
	echo "Fizz"
	
     elif ! (( i % 5 ))
	then
	    echo "buzz"
     else
	    echo "$i"
       
     fi
    ((i++))
done
