#!/usr/bin/env bash
# making while loop with if elif and else
i=1

while [ $i -le 10 ] 
do
   
    if [[ "$i" == 4 ]]; then
       
	echo "Bad Luck" 
	elif [[ "$i" == 8 ]]; then
	echo "Good Luck"
    else
	echo "Holberton School"
    fi
    ((i++))
       done
	
