#!/usr/bin/env bash
# Custome header X-Served-By


sudo apt-get -y update
sudo apt-get -y  install nginx
echo 'Hello World' | sudo tee /var/www/html/index.html
sudo ufw allow nginx
sudo service nginx start
REDIC="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
SRC="/etc/nginx/sites-available/default"
sudo -ie sed "$REDIC" $SRC

FILE=/etc/nginx/sites-available/default
sudo sed -ie "\\\tadd_header X-Served-By \$HOSTNAME;" $FILE
sudo service nginx restart
